import Link from "next/link";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Reveal from "@/components/Reveal";
import Story from "@/components/Story";
import ScanStory from "@/components/ScanStory";
import Visual from "@/components/Visual";
import { site } from "@/lib/site";

export default function Home(){const schema={"@context":"https://schema.org","@type":site.businessType,"name":site.name,"url":site.url,"description":"Empresa constructora en Madrid para obra nueva, rehabilitación y estructuras de hormigón, con coordinación técnica de las fases de ejecución.","areaServed":site.city,"makesOffer":site.services.map(s=>({"@type":"Offer","itemOffered":{"@type":"Service","name":s.title}}))};return <><NavBar/><main>
 <section className="hero construction-hero"><div className="tech-grid"/><div className="shell hero-grid"><div className="hero-copy"><div className="tech-code">COTA / MAD / 001</div><p className="eyebrow">CONSTRUCCIÓN + EJECUCIÓN TÉCNICA</p><h1>Construir es coordinar lo que todavía no se ve.</h1><p className="lead">Obra nueva, rehabilitación y estructuras en Madrid con planificación técnica, control de fases y coordinación de los oficios que hacen posible cada proyecto.</p><div className="hero-actions"><Link className="button primary" href="/contacto">// INICIAR PROYECTO</Link><Link className="button ghost" href="#story">VER SECUENCIA ↓</Link></div></div><div className="hero-art"><Visual/></div></div><div className="shell datum-line"><span>LAT 40.4168</span><span>LONG -3.7038</span><span>REV. 01</span><span>STATUS / DEMO</span></div></section>
 <section id="servicios" className="section shell construction-services"><div className="section-index">[ 01 ]</div><Reveal><p className="eyebrow">CAPACIDADES</p><h2 className="display">Tres líneas de trabajo. Un mismo sistema de control.</h2></Reveal><div className="service-grid"><Link href="/servicios/obra-nueva" className="service-card"><span>01</span><h3>OBRA NUEVA</h3><p>De cimentación a acabados con coordinación de estructura, envolvente e instalaciones.</p><b>OPEN ↗</b></Link><Link href="/servicios/rehabilitacion-edificios" className="service-card"><span>02</span><h3>REHABILITACIÓN</h3><p>Intervención sobre edificios existentes, cubiertas, fachadas y elementos constructivos.</p><b>OPEN ↗</b></Link><Link href="/servicios/estructuras-hormigon" className="service-card"><span>03</span><h3>HORMIGÓN</h3><p>Replanteo, ferralla, encofrado, vertido y control de estructuras de hormigón armado.</p><b>OPEN ↗</b></Link></div></section>
 <Story/>
 <section className="section shell control-section"><div className="section-index">[ 02 ]</div><div className="control-head"><p className="eyebrow">CONTROL DE OBRA</p><h2>No medimos el avance solo en metros construidos.</h2></div><div className="control-grid"><Reveal><b>01</b><h3>Secuencia</h3><p>Cada oficio entra cuando el soporte y las decisiones previas están realmente preparados.</p></Reveal><Reveal><b>02</b><h3>Interferencias</h3><p>Instalaciones, estructura y cerramientos se coordinan antes de que un conflicto llegue a obra.</p></Reveal><Reveal><b>03</b><h3>Revisión</h3><p>Los puntos críticos se verifican por fases para no depender de correcciones al final.</p></Reveal><Reveal><b>04</b><h3>Entrega</h3><p>Pruebas, documentación y repasos forman parte del cierre técnico del proyecto.</p></Reveal></div></section>
 <ScanStory/>
 <section className="section shell seo-tech"><div className="section-index">[ 03 ]</div><div><p className="eyebrow">ARQUITECTURA SEO</p><h2>Páginas específicas para búsquedas específicas.</h2></div><div><p>La demo incorpora URLs independientes para obra nueva, rehabilitación y estructuras de hormigón en Madrid. Cada página tiene contenido propio, metadatos, canonical, Schema.org y enlaces relacionados.</p><p>La estructura puede ampliarse de forma modular con proyectos, tipologías y áreas de servicio cuando exista información suficiente para aportar valor real al usuario.</p></div></section>
 <section className="cta-band"><div className="shell"><p className="tech-code">COTA / NEXT PROJECT</p><h2>DEL PLANO A OBRA.</h2><Link className="button light" href="/contacto">SOLICITAR INFORMACIÓN ↗</Link></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
