import Link from "next/link";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Reveal from "@/components/Reveal";
import Story from "@/components/Story";
import Visual from "@/components/Visual";
import { site } from "@/lib/site";

export default function Home(){
 const schema={"@context":"https://schema.org","@type":site.businessType,"name":site.name,"url":site.url,"description":"Obra nueva, rehabilitación y construcción residencial con seguimiento técnico de cada fase. Coordinamos estructura, envolvente, instalaciones y acabados dentro de un proceso común.","areaServed":site.city,"makesOffer":site.services.map(s=>({"@type":"Offer","itemOffered":{"@type":"Service","name":s.title}}))};
 return <><NavBar/><main>
 <section className="hero"><div className="hero-orb"/><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">CONSTRUCCIÓN · MADRID</p><h1>Del terreno a la última entrega.</h1><p className="lead">Obra nueva, rehabilitación y construcción residencial con seguimiento técnico de cada fase. Coordinamos estructura, envolvente, instalaciones y acabados dentro de un proceso común.</p><div className="hero-actions"><Link className="button primary" href="/contacto">Habla de tu proyecto</Link><Link className="button ghost" href="#servicios">Ver servicios</Link></div></div><div className="hero-art"><Visual stage={0}/></div></div><div className="shell stats"><div><strong>01</strong><span>Planificación técnica</span></div><div><strong>02</strong><span>Coordinación de gremios</span></div><div><strong>03</strong><span>Control de ejecución</span></div></div></section>
 <section id="servicios" className="section shell"><Reveal><p className="eyebrow">SERVICIOS</p><h2 className="display">Contenido útil para usuarios y buscadores.</h2><p className="section-intro">Cada servicio dispone de su propia URL, encabezado principal, texto especializado, metadatos y enlazado interno. La estructura está pensada para crecer con nuevas zonas o servicios.</p></Reveal><div className="service-grid"><Link href="/servicios/obra-nueva" className="service-card"><span>01</span><h3>Construcción de obra nueva en Madrid</h3><p>Ejecución de viviendas y proyectos residenciales desde cimentación hasta acabados, con coordinación técnica de todas las fases.</p><b>Ver servicio →</b></Link><Link href="/servicios/rehabilitacion-edificios" className="service-card"><span>02</span><h3>Rehabilitación de edificios en Madrid</h3><p>Intervenciones de rehabilitación para actualizar envolventes, zonas comunes, cubiertas y elementos constructivos deteriorados.</p><b>Ver servicio →</b></Link><Link href="/servicios/estructuras-hormigon" className="service-card"><span>03</span><h3>Estructuras de hormigón en Madrid</h3><p>Ejecución y coordinación de estructuras de hormigón armado para proyectos residenciales y de construcción.</p><b>Ver servicio →</b></Link></div></section>
 <Story/>
 <section className="section shell"><div className="split-title"><p className="eyebrow">POSICIONAMIENTO ORGÁNICO</p><h2>SEO que empieza por explicar bien el servicio.</h2></div><div className="seo-grid"><Reveal className="seo-card"><h3>Construcción coordinada desde la primera fase</h3><p>La eficiencia de una obra depende en gran parte de la secuencia. Una instalación que llega tarde o una solución constructiva que no se ha coordinado puede generar retrabajos. Por eso planificamos cada fase con visión del conjunto.</p></Reveal><Reveal className="seo-card"><h3>Obra nueva y rehabilitación con control técnico</h3><p>Trabajamos tanto en proyectos de nueva construcción como en rehabilitación, adaptando el proceso al estado del inmueble, la documentación técnica y las necesidades de cada intervención.</p></Reveal></div></section>
 <section className="cta-band"><div className="shell"><p className="eyebrow">MADRID</p><h2>Construimos con método. Entregamos con detalle.</h2><p>La ubicación, la marca y los datos de contacto están centralizados para que puedas adaptar esta plantilla a un proyecto real.</p><Link className="button light" href="/contacto">Solicitar información</Link></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>
}
